# Register a new user
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
  "name": "John Doe",
  "username": "john_doe",
  "password": "password123",
  "email": "johndoe@example.com",
  "notesPassword": "note123",
  "confirmNotesPassword": "note123"
}
###
# Login to obtain JWT token
POST http://localhost:3000/user-api/users/login
Content-Type: application/json

{
  "username": "vignesh",
  "password": "aditya"
}

### Get all users (Protected)
GET http://localhost:3000/user-api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJpYXQiOjE3MjU3OTc5ODUsImV4cCI6MTcyNTg4NDM4NX0.My5p0TZ4zBcbS0SUzOaUSYaVRqhkEuE_reYpSctu56E

### Create a new note (Protected)
POST http://localhost:3000/user-api/users/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJpYXQiOjE3MjU3MDkyNzMsImV4cCI6MTcyNTc5NTY3M30.i54kayCczNcHkFAt5K4KnO8EOzrHcMYmtpecv4Sts8c
Content-Type: application/json

{
  "title": "sv",
  "content": "This is the content of my sv note.",
  "tags": ["Work"],
  "password": "vignesh"
}

### Get all notes for the logged-in user (Protected)
GET http://localhost:3000/user-api/users/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJpYXQiOjE3MjU2OTMxMzcsImV4cCI6MTcyNTc3OTUzN30.zsweHOjSFmAc5J1sOh7CXNgZSWHqPe8hnLA0C6LIrGA
### Fetch notes with a specific tag (Protected)
GET http://localhost:3000/user-api/users/notes/tag/Work
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJpYXQiOjE3MjU2OTYwMjIsImV4cCI6MTcyNTc4MjQyMn0.vaFTVNdlWJcsi-CAWnGYvriRM93Htjri3dsq59lm_5M


### Mark a note as favorite (Protected)
  PUT http://localhost:3000/user-api/users/notes/favorite/2024-09-01T06:22:40.090Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJpYXQiOjE3MjUxOTI0MjUsImV4cCI6MTcyNTE5NjAyNX0.MCla2g4KXPnFgPzlkNLbytbZgegws8RDGi3Rg8BwX1k

### Unmark a note as favorite (Protected)
PUT http://localhost:3000/user-api/users/notes/unfavorite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJpYXQiOjE3MjUxOTI0MjUsImV4cCI6MTcyNTE5NjAyNX0.MCla2g4KXPnFgPzlkNLbytbZgegws8RDGi3Rg8BwX1k
### Move a note to the recycle bin (Protected)
PUT http://localhost:3000/user-api/users/notes/delete/2024-08-24T09:18:18.051Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5fZG9lIiwiaWF0IjoxNzI0NDkxMDQzLCJleHAiOjE3MjQ0OTQ2NDN9.bG3yp4NFhsQSFKTfk-S9taxPTy5c9UgVYYaFIfPzXIs


### Get all notes in the recycle bin (Protected)
GET http://localhost:3000/user-api/users/notes/recycle-bin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5fZG9lIiwiaWF0IjoxNzI0NDkxMDQzLCJleHAiOjE3MjQ0OTQ2NDN9.bG3yp4NFhsQSFKTfk-S9taxPTy5c9UgVYYaFIfPzXIs


### Undo delete (restore a note from recycle bin) (Protected)
PUT http://localhost:3000/user-api/users/notes/undo-delete/2024-08-24T09:18:18.051Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5fZG9lIiwiaWF0IjoxNzI0NDkxMDQzLCJleHAiOjE3MjQ0OTQ2NDN9.bG3yp4NFhsQSFKTfk-S9taxPTy5c9UgVYYaFIfPzXIs

### Fetch all favorite notes for the logged-in user (Protected)
GET http://localhost:3000/user-api/users/notes/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJpYXQiOjE3MjU1OTI0MzQsImV4cCI6MTcyNTY3ODgzNH0._aR5OpE8SQgzQEUt4TdhC2oizzIxFsH6pTbGoKEyqB0

### Get the username of the current logged-in user (Protected)
GET http://localhost:3000/user-api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJpYXQiOjE3MjUxOTI0MjUsImV4cCI6MTcyNTE5NjAyNX0.MCla2g4KXPnFgPzlkNLbytbZgegws8RDGi3Rg8BwX1k
###
GET http://localhost:3000/user-api/users/notes/2024-08-30T14:14:07.198Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJpYXQiOjE3MjUxOTI0MjUsImV4cCI6MTcyNTE5NjAyNX0.MCla2g4KXPnFgPzlkNLbytbZgegws8RDGi3Rg8BwX1k

### Update a note (Protected)
PUT http://localhost:3000/user-api/users/notes/2024-09-05T14:19:13.810Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJpYXQiOjE3MjU1NDU5MzcsImV4cCI6MTcyNTYzMjMzN30.bVUJw5XnXQGKADEng4ytt_tKGtOWXjdcgb-_QGGBQXQ
Content-Type: application/json

{
  "title": "Updated Note Title",
  "content": "This is the updated content of my note.",
  "tags": ["work"]
}

### Permanently Delete a Note
DELETE http://localhost:3000/user-api/users/notes/permanent-delete/2024-09-05T14:19:22.691Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJpYXQiOjE3MjU2OTMxMzcsImV4cCI6MTcyNTc3OTUzN30.zsweHOjSFmAc5J1sOh7CXNgZSWHqPe8hnLA0C6LIrGA

Content-Type: application/json

### Change Notes Password
### Change Notes Password
PUT http://localhost:3000/user-api/users/change-notes-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJpYXQiOjE3MjU3ODAwMzQsImV4cCI6MTcyNTg2NjQzNH0.U0aTsLzv5Ssa4vY09MYAPme7P1PiCHR-VOzJqUt58Io
Content-Type: application/json

{
    "oldPassword": "fakru",
    "newPassword": "vignesh",
    "confirmNewPassword": "vignesh"
}

### Change User Password
PUT http://localhost:3000/user-api/users/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJpYXQiOjE3MjU3ODAwMzQsImV4cCI6MTcyNTg2NjQzNH0.U0aTsLzv5Ssa4vY09MYAPme7P1PiCHR-VOzJqUt58Io
Content-Type: application/json

{
  "oldPassword": "aditya",
  "newPassword": "aditya",
  "confirmNewPassword": "aditya"
}
