### Users API Requests

### -> Login
POST http://localhost:3000/user-api/users/login
Content-Type: application/json

{
    "username": "fakru",
    "password": "12345678"
}

### -> Get All Users
GET http://localhost:3000/user-api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha3J1IiwiaWF0IjoxNzI0MzM4MDk0LCJleHAiOjE3MjQzNDE2OTR9.iY-yDbEyRLLFeZ9Q_BkyHkUdPkp6L_5tPnwyJ9FzuKM

### -> Create New User
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "name": "Fakru",
    "username": "fakru",
    "password": "12345678",
    "email": "fakru@gmail.com"
}
###
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "name": "vvsv",
    "username": "vvsv",
    "password": "12345678",
    "email": "vvsv@gmail.com"
}

### -> Create a New Note
POST http://localhost:3000/user-api/users/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha3J1IiwiaWF0IjoxNzI0MzM4MDk0LCJleHAiOjE3MjQzNDE2OTR9.iY-yDbEyRLLFeZ9Q_BkyHkUdPkp6L_5tPnwyJ9FzuKM
Content-Type: application/json

{
    "title": "Note1",
    "content": "This is the work content of the first note.",
    "tags": ["work"]
}
### -> Create a New Note
POST http://localhost:3000/user-api/users/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha3J1IiwiaWF0IjoxNzI0MzM4MDk0LCJleHAiOjE3MjQzNDE2OTR9.iY-yDbEyRLLFeZ9Q_BkyHkUdPkp6L_5tPnwyJ9FzuKM
Content-Type: application/json

{
    "title": "Note4",
    "content": "This is the work content of the first note.",
    "tags": [""]
}
###
POST http://localhost:3000/user-api/users/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha3J1IiwiaWF0IjoxNzI0MzM4MDk0LCJleHAiOjE3MjQzNDE2OTR9.iY-yDbEyRLLFeZ9Q_BkyHkUdPkp6L_5tPnwyJ9FzuKM
Content-Type: application/json

{
    "title": "Note2",
    "content": "This note should be added to personal tag.",
    "tags": ["personal"]
}

### -> Get All Notes for Logged-In User 
GET http://localhost:3000/user-api/users/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha3J1IiwiaWF0IjoxNzI0MzM4MDk0LCJleHAiOjE3MjQzNDE2OTR9.iY-yDbEyRLLFeZ9Q_BkyHkUdPkp6L_5tPnwyJ9FzuKM

### Fetch Notes with "Personal" Tag
GET http://localhost:3000/user-api/users/notes/tag/personal
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha3J1IiwiaWF0IjoxNzI0MzM4MDk0LCJleHAiOjE3MjQzNDE2OTR9.iY-yDbEyRLLFeZ9Q_BkyHkUdPkp6L_5tPnwyJ9FzuKM
### Fetch Notes with "Work" Tag
GET http://localhost:3000/user-api/users/notes/tag/work
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha3J1IiwiaWF0IjoxNzI0MzM4MDk0LCJleHAiOjE3MjQzNDE2OTR9.iY-yDbEyRLLFeZ9Q_BkyHkUdPkp6L_5tPnwyJ9FzuKM

### Mark Note as Favorite
PUT http://localhost:3000/user-api/users/notes/favorite/2024-08-22T14:50:37.330Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha3J1IiwiaWF0IjoxNzI0MzM4MDk0LCJleHAiOjE3MjQzNDE2OTR9.iY-yDbEyRLLFeZ9Q_BkyHkUdPkp6L_5tPnwyJ9FzuKM

### Unmark Note as Favorite
PUT http://localhost:3000/user-api/users/notes/unfavorite/2024-08-22T14:50:37.330Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha3J1IiwiaWF0IjoxNzI0MzM4MDk0LCJleHAiOjE3MjQzNDE2OTR9.iY-yDbEyRLLFeZ9Q_BkyHkUdPkp6L_5tPnwyJ9FzuKM

### Fetch Favorite Notes
GET http://localhost:3000/user-api/users/notes/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha3J1IiwiaWF0IjoxNzI0MzM4MDk0LCJleHAiOjE3MjQzNDE2OTR9.iY-yDbEyRLLFeZ9Q_BkyHkUdPkp6L_5tPnwyJ9FzuKM

### Delete Note (move to recycle bin)
PUT http://localhost:3000/user-api/users/notes/delete/2024-08-22T14:50:37.330Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha3J1IiwiaWF0IjoxNzI0MzM4MDk0LCJleHAiOjE3MjQzNDE2OTR9.iY-yDbEyRLLFeZ9Q_BkyHkUdPkp6L_5tPnwyJ9FzuKM

### Get Notes in Recycle Bin
GET http://localhost:3000/user-api/users/notes/recycle-bin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha3J1IiwiaWF0IjoxNzI0MzM4MDk0LCJleHAiOjE3MjQzNDE2OTR9.iY-yDbEyRLLFeZ9Q_BkyHkUdPkp6L_5tPnwyJ9FzuKM

### Undo Delete (Restore Note from Recycle Bin)
PUT http://localhost:3000/user-api/users/notes/undo-delete/2024-08-22T14:50:37.330Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha3J1IiwiaWF0IjoxNzI0MzM4MDk0LCJleHAiOjE3MjQzNDE2OTR9.iY-yDbEyRLLFeZ9Q_BkyHkUdPkp6L_5tPnwyJ9FzuKM
